<?php
function bakery_user_menu() {
    $items['welcome'] = array(
        'title' => 'Hi There!',
        'page callback' => 'welcome_new_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}



function bakery_user_user_login(&$edit, $account, $category) {
    $_GET['destination'] = 'welcome_new_user';
}

function bakery_user_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id == 'comment_node_page_form') {
        $form['subject'] = FALSE;
    }
}
